# Generated by Django 4.2.1 on 2023-05-10 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='outgoing_friend_requests',
            field=models.ManyToManyField(blank=True, related_name='incoming_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
